/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */

export type GetUserErrorsApiTrainingErrorsGetParams = {
error_type?: string | null;
user_id?: number | null;
skip?: number;
limit?: number;
};
