/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */

export type ListWordComponentsApiComponentsGetParams = {
query?: string;
type?: string;
word_id?: number;
limit?: number;
offset?: number;
};
