/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { WordComponentResponse } from './wordComponentResponse';
import type { PaginatedWordComponentResponseNextOffset } from './paginatedWordComponentResponseNextOffset';

export interface PaginatedWordComponentResponse {
  items: WordComponentResponse[];
  next_offset: PaginatedWordComponentResponseNextOffset;
  total_count: number;
}
