/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { PhraseResponse } from './phraseResponse';
import type { PaginatedPhraseResponseNextOffset } from './paginatedPhraseResponseNextOffset';

export interface PaginatedPhraseResponse {
  items: PhraseResponse[];
  next_offset: PaginatedPhraseResponseNextOffset;
  total_count: number;
}
