/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { UserAnswerError } from './userAnswerError';
import type { PaginatedUserAnswerErrorResponseNextOffset } from './paginatedUserAnswerErrorResponseNextOffset';

export interface PaginatedUserAnswerErrorResponse {
  items: UserAnswerError[];
  next_offset: PaginatedUserAnswerErrorResponseNextOffset;
  total_count: number;
}
