/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { PhraseMeaningUpdateId } from './phraseMeaningUpdateId';
import type { PhraseMeaningUpdateMeaning } from './phraseMeaningUpdateMeaning';
import type { PhraseMeaningUpdateExamples } from './phraseMeaningUpdateExamples';

export interface PhraseMeaningUpdate {
  id?: PhraseMeaningUpdateId;
  meaning?: PhraseMeaningUpdateMeaning;
  examples?: PhraseMeaningUpdateExamples;
}
