/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { PhraseDetailResponseCategories } from './phraseDetailResponseCategories';
import type { PhraseDetailResponseCategoryNames } from './phraseDetailResponseCategoryNames';
import type { PhraseDetailResponseLevel } from './phraseDetailResponseLevel';
import type { PhraseDetailResponseFrequency } from './phraseDetailResponseFrequency';
import type { WordResponse } from './wordResponse';
import type { PhraseMeaningResponse } from './phraseMeaningResponse';

export interface PhraseDetailResponse {
  id: number;
  categories?: PhraseDetailResponseCategories;
  category_names?: PhraseDetailResponseCategoryNames;
  level?: PhraseDetailResponseLevel;
  frequency?: PhraseDetailResponseFrequency;
  words: WordResponse[];
  labels: string[];
  word_count: number;
  value_count: number;
  meanings?: PhraseMeaningResponse[];
  translations: string[];
  components: string[];
}
