/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { PhraseResponseCategories } from './phraseResponseCategories';
import type { PhraseResponseCategoryNames } from './phraseResponseCategoryNames';
import type { PhraseResponseLevel } from './phraseResponseLevel';
import type { PhraseResponseFrequency } from './phraseResponseFrequency';
import type { WordResponse } from './wordResponse';
import type { PhraseMeaningResponse } from './phraseMeaningResponse';

export interface PhraseResponse {
  id: number;
  categories?: PhraseResponseCategories;
  category_names?: PhraseResponseCategoryNames;
  level?: PhraseResponseLevel;
  frequency?: PhraseResponseFrequency;
  words: WordResponse[];
  labels: string[];
  word_count: number;
  value_count: number;
  meanings?: PhraseMeaningResponse[];
}
