/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { PhraseUpdateWords } from './phraseUpdateWords';
import type { PhraseUpdateCategories } from './phraseUpdateCategories';
import type { PhraseUpdateCategoryNames } from './phraseUpdateCategoryNames';
import type { PhraseUpdateLevel } from './phraseUpdateLevel';
import type { PhraseUpdateFrequency } from './phraseUpdateFrequency';
import type { PhraseUpdateLabels } from './phraseUpdateLabels';
import type { PhraseUpdateMeanings } from './phraseUpdateMeanings';

export interface PhraseUpdate {
  words?: PhraseUpdateWords;
  categories?: PhraseUpdateCategories;
  category_names?: PhraseUpdateCategoryNames;
  level?: PhraseUpdateLevel;
  frequency?: PhraseUpdateFrequency;
  labels?: PhraseUpdateLabels;
  meanings?: PhraseUpdateMeanings;
}
