/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { PhraseMeaningExampleUpdateId } from './phraseMeaningExampleUpdateId';
import type { PhraseMeaningExampleUpdateExampleText } from './phraseMeaningExampleUpdateExampleText';
import type { PhraseMeaningExampleUpdateExampleTextGerman } from './phraseMeaningExampleUpdateExampleTextGerman';

export interface PhraseMeaningExampleUpdate {
  id?: PhraseMeaningExampleUpdateId;
  example_text?: PhraseMeaningExampleUpdateExampleText;
  example_text_german?: PhraseMeaningExampleUpdateExampleTextGerman;
}
