/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileUpdateEntryTestResultAnyOf } from './profileUpdateEntryTestResultAnyOf';

export type ProfileUpdateEntryTestResult = ProfileUpdateEntryTestResultAnyOf | null;
