/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileUpdateIsPublic } from './profileUpdateIsPublic';
import type { ProfileUpdateTargetLevel } from './profileUpdateTargetLevel';
import type { ProfileUpdateCategories } from './profileUpdateCategories';
import type { ProfileUpdateRegion } from './profileUpdateRegion';
import type { ProfileUpdateLearningSpeed } from './profileUpdateLearningSpeed';
import type { ProfileUpdateEntryTestResult } from './profileUpdateEntryTestResult';
import type { ProfileUpdateDailyMinutes } from './profileUpdateDailyMinutes';
import type { ProfileUpdateDesiredLevel } from './profileUpdateDesiredLevel';
import type { ProfileUpdateCurrentLevel } from './profileUpdateCurrentLevel';
import type { ProfileUpdateCategoryNames } from './profileUpdateCategoryNames';

export interface ProfileUpdate {
  is_public: ProfileUpdateIsPublic;
  target_level: ProfileUpdateTargetLevel;
  categories: ProfileUpdateCategories;
  region: ProfileUpdateRegion;
  learning_speed: ProfileUpdateLearningSpeed;
  entry_test_result: ProfileUpdateEntryTestResult;
  daily_minutes: ProfileUpdateDailyMinutes;
  desired_level: ProfileUpdateDesiredLevel;
  current_level: ProfileUpdateCurrentLevel;
  category_names?: ProfileUpdateCategoryNames;
}
