/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */

export type SearchMistakesSearchMistakesGetParams = {
query?: string | null;
category?: number | null;
level?: string | null;
error_type?: string | null;
user_id?: number | null;
item_type?: string | null;
limit?: number;
offset?: number;
};
