/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */

export type SearchPhrasesApiSearchPhrasesGetParams = {
query?: string | null;
category?: string | null;
level?: string | null;
label?: string | null;
word_id?: string | null;
semantic_group_id?: number | null;
part_of_speech?: string | null;
component_text?: string | null;
frequency?: string | null;
word?: string | null;
limit?: number;
offset?: number;
};
