/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */

export type SearchSemanticGroupsApiSearchSemanticGroupsGetParams = {
query?: string | null;
category?: string | null;
level?: string | null;
word_id?: string | null;
phrase_id?: string | null;
frequency?: string | null;
word?: string | null;
limit?: number;
offset?: number;
};
