/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { SemanticGroupCreateWordIds } from './semanticGroupCreateWordIds';
import type { SemanticGroupCreatePhraseIds } from './semanticGroupCreatePhraseIds';
import type { SemanticGroupCreateCategories } from './semanticGroupCreateCategories';
import type { SemanticGroupCreateCategoryNames } from './semanticGroupCreateCategoryNames';
import type { SemanticGroupCreateLevel } from './semanticGroupCreateLevel';
import type { SemanticGroupCreateFrequency } from './semanticGroupCreateFrequency';
import type { SemanticGroupCreateExplanation } from './semanticGroupCreateExplanation';
import type { SemanticGroupCreateDifferenceExplanation } from './semanticGroupCreateDifferenceExplanation';

export interface SemanticGroupCreate {
  name: string;
  word_ids?: SemanticGroupCreateWordIds;
  phrase_ids?: SemanticGroupCreatePhraseIds;
  categories?: SemanticGroupCreateCategories;
  category_names?: SemanticGroupCreateCategoryNames;
  level?: SemanticGroupCreateLevel;
  frequency?: SemanticGroupCreateFrequency;
  explanation?: SemanticGroupCreateExplanation;
  difference_explanation?: SemanticGroupCreateDifferenceExplanation;
}
