/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { StudySetGenerateRequestUserId } from './studySetGenerateRequestUserId';
import type { StudySetGenerateRequestEmail } from './studySetGenerateRequestEmail';
import type { StudySetGenerateRequestRoot } from './studySetGenerateRequestRoot';

export interface StudySetGenerateRequest {
  user_id?: StudySetGenerateRequestUserId;
  email?: StudySetGenerateRequestEmail;
  root?: StudySetGenerateRequestRoot;
}
