/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { TrainingAnswerResponseErrorAnalysis } from './trainingAnswerResponseErrorAnalysis';
import type { TrainingAnswerResponseBriefExplanation } from './trainingAnswerResponseBriefExplanation';

export interface TrainingAnswerResponse {
  is_correct: boolean;
  correct_answer: string;
  error_analysis?: TrainingAnswerResponseErrorAnalysis;
  brief_explanation?: TrainingAnswerResponseBriefExplanation;
}
