/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */

export interface TrainingRateAnswerRequest {
  item_type: string;
  item_id: number;
  rating: number;
  is_review: boolean;
}
