/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { UserCardReviewResponseLastRating } from './userCardReviewResponseLastRating';
import type { UserCardReviewResponseLastAnswer } from './userCardReviewResponseLastAnswer';
import type { UserCardReviewResponseLastResult } from './userCardReviewResponseLastResult';

export interface UserCardReviewResponse {
  id: number;
  user_id: number;
  item_type: string;
  item_id: number;
  last_rating: UserCardReviewResponseLastRating;
  last_answer: UserCardReviewResponseLastAnswer;
  last_result: UserCardReviewResponseLastResult;
  is_review: boolean;
  created_at: string;
  updated_at: string;
}
