/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */

export interface UserAnswerError {
  item_type: string;
  item_id: number;
  correct_answer: string;
  user_answer: string;
  error_analysis: string;
  brief_explanation: string;
  id: number;
  user_id: number;
  created_at: string;
}
