/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { UserPhraseNoteResponseFlag } from './userPhraseNoteResponseFlag';

export interface UserPhraseNoteResponse {
  id: number;
  user_id: number;
  phrase_id: number;
  note: string;
  flag: UserPhraseNoteResponseFlag;
}
