/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { WordBaseGender } from './wordBaseGender';
import type { WordBasePluralForm } from './wordBasePluralForm';
import type { WordBaseVerbForm2 } from './wordBaseVerbForm2';
import type { WordBaseVerbForm3 } from './wordBaseVerbForm3';

export interface WordBase {
  text: string;
  gender?: WordBaseGender;
  plural_form?: WordBasePluralForm;
  verb_form2?: WordBaseVerbForm2;
  verb_form3?: WordBaseVerbForm3;
}
