/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { WordMeaningExampleUpdateId } from './wordMeaningExampleUpdateId';
import type { WordMeaningExampleUpdateExampleText } from './wordMeaningExampleUpdateExampleText';
import type { WordMeaningExampleUpdateExampleTextGerman } from './wordMeaningExampleUpdateExampleTextGerman';

export interface WordMeaningExampleUpdate {
  id?: WordMeaningExampleUpdateId;
  example_text?: WordMeaningExampleUpdateExampleText;
  example_text_german?: WordMeaningExampleUpdateExampleTextGerman;
}
