/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import type { WordUpdateText } from './wordUpdateText';
import type { WordUpdateGender } from './wordUpdateGender';
import type { WordUpdatePluralForm } from './wordUpdatePluralForm';
import type { WordUpdateVerbForm2 } from './wordUpdateVerbForm2';
import type { WordUpdateVerbForm3 } from './wordUpdateVerbForm3';
import type { WordUpdateReflexivity } from './wordUpdateReflexivity';
import type { WordUpdateCase } from './wordUpdateCase';
import type { WordUpdatePartOfSpeech } from './wordUpdatePartOfSpeech';
import type { WordUpdateCategories } from './wordUpdateCategories';
import type { WordUpdateLevel } from './wordUpdateLevel';
import type { WordUpdateFrequency } from './wordUpdateFrequency';

export interface WordUpdate {
  text?: WordUpdateText;
  gender?: WordUpdateGender;
  plural_form?: WordUpdatePluralForm;
  verb_form2?: WordUpdateVerbForm2;
  verb_form3?: WordUpdateVerbForm3;
  reflexivity?: WordUpdateReflexivity;
  case?: WordUpdateCase;
  part_of_speech?: WordUpdatePartOfSpeech;
  categories?: WordUpdateCategories;
  level?: WordUpdateLevel;
  frequency?: WordUpdateFrequency;
}
