version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    build:
      context: ./dr1
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./language-learning-app-frontend-main
    depends_on:
      - backend
    ports:
      - "3000:80"
