/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * German Language Learning API
 * API for managing German words, phrases, components, examples, and semantic groups.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CategoryCreate,
  CategoryResponse,
  GetCategoriesApiCategoriesGetParams,
  HTTPValidationError
} from '.././model';





/**
 * @summary Create Category
 */
export const createCategoryApiCategoriesPost = (
    categoryCreate: CategoryCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryResponse>> => {
    
    
    return axios.default.post(
      `/api/categories`,
      categoryCreate,options
    );
  }



export const getCreateCategoryApiCategoriesPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCategoryApiCategoriesPost>>, TError,{data: CategoryCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createCategoryApiCategoriesPost>>, TError,{data: CategoryCreate}, TContext> => {

const mutationKey = ['createCategoryApiCategoriesPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCategoryApiCategoriesPost>>, {data: CategoryCreate}> = (props) => {
          const {data} = props ?? {};

          return  createCategoryApiCategoriesPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCategoryApiCategoriesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCategoryApiCategoriesPost>>>
    export type CreateCategoryApiCategoriesPostMutationBody = CategoryCreate
    export type CreateCategoryApiCategoriesPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Category
 */
export const useCreateCategoryApiCategoriesPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCategoryApiCategoriesPost>>, TError,{data: CategoryCreate}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCategoryApiCategoriesPost>>,
        TError,
        {data: CategoryCreate},
        TContext
      > => {

      const mutationOptions = getCreateCategoryApiCategoriesPostMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * @summary Get Categories
 */
export const getCategoriesApiCategoriesGet = (
    params?: GetCategoriesApiCategoriesGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryResponse[]>> => {
    
    
    return axios.default.get(
      `/api/categories`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetCategoriesApiCategoriesGetQueryKey = (params?: GetCategoriesApiCategoriesGetParams,) => {
    return [`/api/categories`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCategoriesApiCategoriesGetQueryOptions = <TData = Awaited<ReturnType<typeof getCategoriesApiCategoriesGet>>, TError = AxiosError<HTTPValidationError>>(params?: GetCategoriesApiCategoriesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCategoriesApiCategoriesGet>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCategoriesApiCategoriesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategoriesApiCategoriesGet>>> = ({ signal }) => getCategoriesApiCategoriesGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCategoriesApiCategoriesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCategoriesApiCategoriesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCategoriesApiCategoriesGet>>>
export type GetCategoriesApiCategoriesGetQueryError = AxiosError<HTTPValidationError>


/**
 * @summary Get Categories
 */

export function useGetCategoriesApiCategoriesGet<TData = Awaited<ReturnType<typeof getCategoriesApiCategoriesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: GetCategoriesApiCategoriesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCategoriesApiCategoriesGet>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCategoriesApiCategoriesGetQueryOptions(params,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



