"""initial snapshot

Revision ID: 3c79cbbbc34d
Revises: 
Create Date: 2025-05-11 22:23:41.664724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c79cbbbc34d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_meaning_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meaning_id', sa.Integer(), nullable=True),
    sa.Column('translation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meaning_id'], ['word_meanings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_meaning_translations')
    # ### end Alembic commands ###
