"""add example_text_german to phrase_meaning_example and explanation to semantic_group

Revision ID: 9ccbb7e3b591
Revises: 3c79cbbbc34d
Create Date: 2025-05-22 10:30:48.090015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ccbb7e3b591'
down_revision: Union[str, None] = '3c79cbbbc34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_meaning_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meaning_id', sa.Integer(), nullable=True),
    sa.Column('translation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meaning_id'], ['word_meanings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('phrase_meaning_examples', sa.Column('example_text_german', sa.String(), nullable=True))
    op.add_column('semantic_groups', sa.Column('explanation', sa.String(), nullable=True))
    op.alter_column('special_user_study_sets', 'root',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_special_user_study_sets_id'), 'special_user_study_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_special_user_study_sets_id'), table_name='special_user_study_sets')
    op.alter_column('special_user_study_sets', 'root',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('semantic_groups', 'explanation')
    op.drop_column('phrase_meaning_examples', 'example_text_german')
    op.drop_table('word_meaning_translations')
    # ### end Alembic commands ###
